stages:
  - test
  - build image
  - trigger deploy
  - veracode scan
  - deps scan
  - pages

variables:
  MYSQL_ROOT_PASSWORD: "root"
  MYSQL_DATABASE: "director_test"
  MYSQL_USER: "director"
  MYSQL_PASSWORD: "director"
  VAULT_ADDR: "http://vault.sit-ota.aws.in.here.com"

default:
  services:
    - name: mariadb:10.1
      alias: db
      command:
        - --character-set-server=utf8
        - --collation-server=utf8_unicode_ci
        - --max_connections=1000

test:
  stage: test
  tags:
    - docker-sock
  image: advancedtelematic/gitlab-jobs:0.2.0
  variables:
    DB_URL: "jdbc:mariadb://db:3306/$MYSQL_DATABASE"
  before_script:
    - echo "GRANT ALL PRIVILEGES ON \`director_test%\`.* TO 'director'@'%'; FLUSH PRIVILEGES; " > db_user.sql
    - mysqladmin ping --protocol=TCP -h db -P 3306 -u root -proot
    - mysql -v -h db -u root -proot < db_user.sql
  script:
    - ./sbt -sbt-dir ./.sbt -ivy ./.ivy2 clean coverage compile test coverageReport
  cache:
    paths:
      - .ivy2/
      - .sbt

build docker image:
  stage: build image
  only:
    - master
  tags:
    - docker-sock
  image: advancedtelematic/gitlab-jobs:0.2.0
  script:
    - env | sort
    - export VAULT_TOKEN=$(cat /opt/vault/token)
    - gitlab-docker-login $VAULT_ADDR
    - ./sbt -x -sbt-dir ./.sbt -ivy ./.ivy2 -batch release with-defaults
  cache:
    paths:
      - .ivy2/
      - .sbt/

trigger dev deploy:
  stage: trigger deploy
  only:
    - master
  variables:
    ENV: "dev"
    NEW_TAG: $CI_COMMIT_SHA
    SERVICE: director
    CREATE_COMMIT: "true"
  trigger:
    project: OLP/EDGE/OTA/infra/deployment-descriptors
    branch: master

trigger sit deploy:
  stage: trigger deploy
  only:
    - deploy/sit
  variables:
    ENV: "sit"
    NEW_TAG: $CI_COMMIT_SHA
    SERVICE: director
    CREATE_COMMIT: "true"
  trigger:
    project: OLP/EDGE/OTA/infra/deployment-descriptors
    branch: master

deps scan:
  # perform dependencies CVE analysis
  stage: deps scan
  only:
    - schedules
  image: advancedtelematic/gitlab-jobs:0.1.0
  script:
    - ./sbt dependencyCheckAggregate
    - mv target/scala-*/dependency-check-report.html ./depchk.html
  artifacts:
    paths:
      - depchk.html

pages:
  stage: pages
  only:
    - schedules
  dependencies:
    - deps scan
  script:
    - mkdir -p public
    - mv depchk.html public/index.html
  artifacts:
    paths:
      - public
    expire_in: 64 days

veracode scan:
  # prepare and submit for static code analysis
  stage: veracode scan
  only:
    variables:
      - $VERACODE_API_ID
  image: advancedtelematic/veracode:0.1.1
  before_script:
    - ./sbt package
  script:
    - run-veracode.sh
  artifacts:
    paths:
      - /tmp/package.zip
