ALTER TABLE `multi_target_updates`
ADD COLUMN `namespace` varchar(200) NOT NULL,
ADD `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

